#!/usr/bin/python3 

# How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

def compute():
    distinct_terms = set()

    for a in range(2, 101):
        for b in range(2, 101):
            distinct_terms.add(a**b)

    return len(distinct_terms)

if __name__ == "__main__":
    print(compute())    
